---

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest


- name: Install PostgreSQL
  become: yes
  apt:
    name: "postgresql"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - postgresql
    - db
    - deps

- name: Install dependencies for the Ansible module
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-psycopg2
  tags:
    - postgresql
    - db
    - deps
